server:
  port: 28082

spring:
  application:
    name: sca-rocketmq-consumer
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876 #rocketmq 服务地址
        bindings:
          input1: {consumer.orderly: true}  #是否排序
          input2: {consumer.orderly: false, consumer.tags: tagStr}  #是否排序 #订阅 带tag值为tagStr的字符串
          input3: {consumer.tags: tagObj}   #订阅 带tag值为tabObj的字符串
      bindings:
        input1: {destination: test-topic, content-type: text/plain, group: test-group1}
        input2: {destination: test-topic, content-type: text/plain, group: test-group2, consumer.concurrency: 20, consumer.maxAttempts: 1}
        input3: {destination: test-topic, content-type: application/json, group: test-group3, consumer.concurrency: 20}
        input4: {destination: tx-topic, content-type: text/plain, group: tx-group, consumer.concurrency: 5}
        input5: {destination: pull-topic, content-type: text/plain, group: pull-group, consumer.maxAttempts: 1}


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always